<?php

namespace CollaborateurBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNb()
    {
        return $this->createQueryBuilder('role')
            ->select('COUNT(role.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
