index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

projet:
  resource: "@ProjetBundle/Controller/"
  type:     annotation
  prefix:   /

collaborateur:
  resource: "@CollaborateurBundle/Controller/"
  type:     annotation
  prefix:   /


fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"