<?php

namespace ClientBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNb()
    {
        return $this->createQueryBuilder('client')
        ->select('COUNT(client.id)')
        ->getQuery()
        ->getSingleScalarResult();
    }
}
