<?php

namespace ProjetBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbProjet()
    {
        return $this->createQueryBuilder('projet')
            ->select('COUNT(projet.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
